Repository dev-oyr/renewal-ourpage, pull requests merged in 2020-02, with the labels that each got.

#8 소개페이지 섹션 2 소개, 스터디, 홈커밍 구현
  package.json
  src/App.js
  src/components/Section2.js
  src/components/Section4.js
  src/datas/histories.json
  src/pages/Main.js
  src/styles/common.scss
  src/styles/section2.scss
  src/styles/section4.scss
  yarn.lock
Labels: 기능 구현

#9 메인 페이지 섹션3 프로젝트 뷰 구현
  package.json
  src/components/CardView.js
  src/components/Section3.js
  src/datas/activities.json
  src/styles/cardview.scss
  src/styles/common.scss
  src/styles/section3.scss
  yarn.lock
Labels: 기능 구현

#10 섹션 1 크기 및 애니메이션 수정
  package.json
  src/App.js
  src/components/CardView.js
  src/components/Section1.js
  src/components/Section2.js
  src/components/Section3.js
  src/components/Section4.js
  src/datas/activities.json
  src/datas/histories.json
  src/pages/Main.js
  src/styles/cardview.scss
  src/styles/common.scss
  src/styles/section1.scss
  src/styles/section2.scss
  src/styles/section3.scss
  src/styles/section4.scss
  yarn.lock
Labels: 기능 개선

#12 소개 페이지 섹션 2 스크롤 개선 및 슬라이드 애니메이션 적용 완료
  src/components/Section2.js
  src/components/Section4.js
  src/components/svg/ic_homecoming.svg
  src/components/svg/ic_introduce.svg
  src/components/svg/ic_study.svg
  src/styles/section2.scss
  src/styles/section4.scss
Labels: 기능 개선

#13 Nav, Footer 컴포넌트 생성 밑 Router분리
  src/App.js
  src/components/CardView.js
  src/components/Footer.js
  src/components/Section3.js
  src/components/Wrapper.js
  src/styles/common.scss
  src/styles/footer.scss
Labels: 기능 구현

#15 섹션 1 구현 완료
  src/components/Section1.js
  src/components/Section2.js
  src/styles/section1.scss
Labels: 기능 개선, 기능 구현

#18 cardPage 파리미터 분류 및 퍼블리싱 완료
  package.json
  src/App.js
  src/components/CardView.js
  src/components/Nav.js
  src/components/Section3.js
  src/datas/activities.json
  src/pages/CardPage.js
  src/styles/cardpage.scss
  src/styles/cardview.scss
  src/styles/footer.scss
  src/styles/section3.scss
  yarn.lock
Labels: 기능 구현

#25 FAQ 페이지 함수형 컴포넌트, 서브라우트 분리 및 퍼블리싱
  src/App.js
  src/components/Accordion.js
  src/components/Nav.js
  src/components/Section3.js
  src/datas/FAQData.json
  src/pages/FAQ.js
  src/styles/accordion.scss
  src/styles/faq.scss
Labels: 기능 개선
